language: 
  node_js
node_js:
    - "node"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
